// <auto-generated/>
#pragma warning disable CS0618
using BlazorWasm.Client.Models;
using BlazorWasm.Client.Odata.Products.Count;
using BlazorWasm.Client.Odata.Products.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace BlazorWasm.Client.Odata.Products
{
    /// <summary>
    /// Builds and executes requests for operations under \odata\Products
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Count property</summary>
        public global::BlazorWasm.Client.Odata.Products.Count.CountRequestBuilder Count
        {
            get => new global::BlazorWasm.Client.Odata.Products.Count.CountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the BlazorWasm.Client.odata.Products.item collection</summary>
        /// <param name="position">製品ID</param>
        /// <returns>A <see cref="global::BlazorWasm.Client.Odata.Products.Item.WithKeyItemRequestBuilder"/></returns>
        public global::BlazorWasm.Client.Odata.Products.Item.WithKeyItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("key", position);
                return new global::BlazorWasm.Client.Odata.Products.Item.WithKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the BlazorWasm.Client.odata.Products.item collection</summary>
        /// <param name="position">製品ID</param>
        /// <returns>A <see cref="global::BlazorWasm.Client.Odata.Products.Item.WithKeyItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::BlazorWasm.Client.Odata.Products.Item.WithKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("key", position);
                return new global::BlazorWasm.Client.Odata.Products.Item.WithKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/odata/Products{?api%2Dversion*,count*,expand*,filter*,orderby*,select*,skip*,top*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/odata/Products{?api%2Dversion*,count*,expand*,filter*,orderby*,select*,skip*,top*}", rawUrl)
        {
        }
        /// <summary>
        /// 製品一覧を取得します。
        /// </summary>
        /// <returns>A <see cref="global::BlazorWasm.Client.Models.ProductIEnumerableODataValue"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::BlazorWasm.Client.Models.ProductIEnumerableODataValue?> GetAsync(Action<RequestConfiguration<global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::BlazorWasm.Client.Models.ProductIEnumerableODataValue> GetAsync(Action<RequestConfiguration<global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::BlazorWasm.Client.Models.ProductIEnumerableODataValue>(requestInfo, global::BlazorWasm.Client.Models.ProductIEnumerableODataValue.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 新しい製品を追加します。
        /// </summary>
        /// <returns>A <see cref="global::BlazorWasm.Client.Models.Product"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::BlazorWasm.Client.Models.Product?> PostAsync(global::BlazorWasm.Client.Models.Product body, Action<RequestConfiguration<global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder.ProductsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::BlazorWasm.Client.Models.Product> PostAsync(global::BlazorWasm.Client.Models.Product body, Action<RequestConfiguration<global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder.ProductsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::BlazorWasm.Client.Models.Product>(requestInfo, global::BlazorWasm.Client.Models.Product.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 製品一覧を取得します。
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// 新しい製品を追加します。
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::BlazorWasm.Client.Models.Product body, Action<RequestConfiguration<global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder.ProductsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::BlazorWasm.Client.Models.Product body, Action<RequestConfiguration<global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder.ProductsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json;odata.streaming=true;IEEE754Compatible=true", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 製品一覧を取得します。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            [QueryParameter("count")]
            public bool? Count { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("expand")]
            public string? Expand { get; set; }
#nullable restore
#else
            [QueryParameter("expand")]
            public string Expand { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("filter")]
            public string Filter { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderby")]
            public string? Orderby { get; set; }
#nullable restore
#else
            [QueryParameter("orderby")]
            public string Orderby { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("select")]
            public string? Select { get; set; }
#nullable restore
#else
            [QueryParameter("select")]
            public string Select { get; set; }
#endif
            [QueryParameter("skip")]
            public int? Skip { get; set; }
            [QueryParameter("top")]
            public int? Top { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// 新しい製品を追加します。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsRequestBuilderPostQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("expand")]
            public string? Expand { get; set; }
#nullable restore
#else
            [QueryParameter("expand")]
            public string Expand { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("select")]
            public string? Select { get; set; }
#nullable restore
#else
            [QueryParameter("select")]
            public string Select { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsRequestBuilderPostRequestConfiguration : RequestConfiguration<global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder.ProductsRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
