// <auto-generated/>
#pragma warning disable CS0618
using BlazorWasm.Client.Odata.Products;
using BlazorWasm.Client.Odata.ProductsWithKey;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BlazorWasm.Client.Odata
{
    /// <summary>
    /// Builds and executes requests for operations under \odata
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OdataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Products property</summary>
        public global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder Products
        {
            get => new global::BlazorWasm.Client.Odata.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BlazorWasm.Client.Odata.OdataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OdataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/odata", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BlazorWasm.Client.Odata.OdataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OdataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/odata", rawUrl)
        {
        }
        /// <summary>
        /// Builds and executes requests for operations under \odata\Products({key})
        /// </summary>
        /// <returns>A <see cref="global::BlazorWasm.Client.Odata.ProductsWithKey.ProductsWithKeyRequestBuilder"/></returns>
        /// <param name="key">製品ID</param>
        public global::BlazorWasm.Client.Odata.ProductsWithKey.ProductsWithKeyRequestBuilder ProductsWithKey(int? key)
        {
            _ = key ?? throw new ArgumentNullException(nameof(key));
            return new global::BlazorWasm.Client.Odata.ProductsWithKey.ProductsWithKeyRequestBuilder(PathParameters, RequestAdapter, key);
        }
    }
}
#pragma warning restore CS0618
